name: "📖 Documentação"
description: "Solicite ajustes ou melhorias na documentação"
title: "[DOC] "
labels: [documentation]
body:
  - type: textarea
    attributes:
      label: Descrição
      description: O que precisa ser atualizado ou criado na documentação?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Onde impacta
      description: Quais arquivos, páginas ou seções precisam mudar?
